import axios from "axios";
import Student from "../../models/Student";
const database =
  "https://psu-library-app-default-rtdb.europe-west1.firebasedatabase.app/";
// this method can be used to add new student object to students object
// each new student object has a unique key generated by default by firebase
export function registerStudent(studentInfo) {
  axios.post(database + "students.json", studentInfo);
}
//this method can be used to get students object,
// then make that students object into an array to be used somewhere else.

// note axios.get is asynchronous --> so it returns promisees:
// promosis are objects that give access to some data later in future.
export async function getStudents() {
  // basically await waits for the promise to happen. ---> returns a promise ....
  const response = await axios.get(database + "students.json");
  //.get returns the students object, which we will turn into an array.
  // this object has key generated by firebase as the key, and individual students objects
  // as values associated with the key.
  let students = [];
  for (const key in response.data) {
    const studentData = response.data[key];
    const student = new Student(
      studentData.FName,
      studentData.LName,
      studentData.Email,
      studentData.psw,
      studentData.borrowedBooks,
      studentData.favBooks
    );
    students.push(student);
  }
  return students;
}
