import axios from "axios";
import Student from "../../models/Student";
const database =
  "https://react-native-course-e10c1-default-rtdb.europe-west1.firebasedatabase.app";
// this method can be used to add new student object to students object
// each new student object has a unique key generated by defualt by firebase
export function registerStudent(studentInfo) {
  axios.post(database + "\\students.json", studentInfo);
}
//this method can be used to get students object,
// then make that studens object into an array to be used somehwere else.

// note axios.get is asycoronis --> so it returns promosises:
// promosis are objects that give access to some data later in future.
export async function getStudents() {
  // basically await waits for the promise to happen. ---> returns a promise ....
  const response = await axios.get(database + "\\students.json");
  //.get returns the students object, which we will turn into an array.
  // this object has key generated by firebase as the key, and indivual students obejects
  // as values associated with the key.
  let studens = [];
  for (const key in response.data) {
    const studentData = response.data[key];
    const student = new Student(
      studentData.FName,
      studentData.LName,
      studentData.Email,
      studentData.psw,
      [],
      []
    );
    studens.push(student);
  }
  return studens;
}
